ModuleName = input("Please enter the module name: ")
FilePath = input("Please enter the Folder path: ")

PrivateFile = open(f"{FilePath}/{ModuleName}_private.h","w")
RegisterFile = open(f"{FilePath}/{ModuleName}_register.h","w")
ConfigFile = open(f"{FilePath}/{ModuleName}_config.h","w")
InterfaceFile = open(f"{FilePath}/{ModuleName}_interface.h","w")
ImplemintationFile = open(f"{FilePath}/{ModuleName}.c","w")

PrivateFile.write(f'#ifndef {ModuleName.upper()}_PRIVATE_H_\n#define {ModuleName.upper()}_PRIVATE_H_\n\n\n\n#endif')
ConfigFile.write(f'#ifndef {ModuleName.upper()}_CONFIG_H_\n#define {ModuleName.upper()}_CONFIG_H_\n\n\n\n#endif')
RegisterFile.write(f'#ifndef {ModuleName.upper()}_REGISTER_H_\n#define {ModuleName.upper()}_REGISTER_H_\n\n\n\n#endif')
ImplemintationFile.write(f'''#include "{ModuleName}_interface.h"\n#include "{ModuleName}_register.h"\n#include "{ModuleName}_private.h"\n#include "{ModuleName}_config.h"\n''')
InterfaceFile.write(f'#ifndef {ModuleName.upper()}_INTERFACE_H_\n#define {ModuleName.upper()}_INTERFACE_H_\n\n\n\n#endif')

PrivateFile.close()
ConfigFile.close()
RegisterFile.close()
InterfaceFile.close()
ImplemintationFile.close()
